sudo: required
services:
- docker
language: go
go:
- '1.7.5'
# Make sure we have p2 and the postgres client.
before_install:
- go get -v github.com/mattn/goveralls
- sudo wget -O /usr/local/bin/p2 https://github.com/wrouesnel/p2cli/releases/download/r4/p2 &&
  sudo chmod +x /usr/local/bin/p2
- sudo wget -O /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.9.0-rc4/docker-compose-Linux-x86_64 &&
  sudo chmod +x /usr/local/bin/docker-compose

script:
- make all
- make docker
- make test-integration
- $HOME/gopath/bin/goveralls -coverprofile=cover.test.out -service=travis-ci
#after_success:
#- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
# Push a tagged build if a tag is found.
#- if [ ! -z "$TRAVIS_TAG" ]; then
#    docker tag wrouesnel/pdns_exporter:latest wrouesnel/pdns_exporter:$TRAVIS_TAG ;
#    docker push wrouesnel/pdns_exporter:$TRAVIS_TAG ;
#  fi
# Push a latest version
#- if [ "$TRAVIS_BRANCH" == "master" ]; then docker push wrouesnel/pdns_exporter ; fi
