language: go
go:
- '1.8'
script:
- make all
- tools/goveralls -coverprofile=cover.test.out -service=travis-ci
deploy:
  provider: releases
  api_key:
    secure: J6AWC4hXvBOF4lWiwzVJKwlv/3cIB3WoPNAtIPWNohOxORfJRjaP36WIsRofhGf31SSDUGltT93ydjQRwcVWS9s5JiC4P8FDJbmYFwrHfF7OIoYULHvtwWX7BmLBim4R/dSKX1oZmlPbuS2rdiR0HanFHMNvyUYJdaZg9c9tTRqNpzEaYnSnBabHVpBrXrzNMEzECfhrShfKuDeDYlNtm9h8KaYta07gKG4uCmuVSEmW67sSvpbgax497jfd4P0ebMe1PMH9mZvGJYK5hQzffPi+J/1XU8iqYloi92Iw+P5Ctmt1Ov8scDnRc0wwsj7pw6aUTY8/V4GS4PvHC2LcL30uhJGm6gbbSTQsSxJMOACJqoLf5nNOiQl0OJmi6LaN+oEIjZdVFTqHWB/UJd0FBdUl4GgRu5BnWtehSWvGrC8KT80JKQV6gMrkCchPkpqnkTpN/XR8fp/f3CdzUt2ax2rIobd8J+cmjKRMIaj6dn5TY0gry16uI1/hfNdPnC/z5Dfwx7eKdfjLNrSlaSpliTcDm5QYKvnClrfXrxLFavBev39uJdXDH8oqlpWHkMABP8wJPOk781jKcp+UnQmZV3GaIaATT+Rl1gc2+pzpkw1uMSbViIE4vNOaQ1SrQqEWSkI5ZdsZ5QPNmHq5X6lBtxLU7SLUNC72qFX2yNv/Y24=
  file: pdns_exporter.x86_64
  on:
    tags: true
    repo: wrouesnel/pdns_exporter
